name: Psalm static analysis

on: [push]

jobs:
  build:
    name: PHP ${{ matrix.php }}, Mode ${{ matrix.mode }}

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: ['8.0', '8.3' ]
        mode: ['stable', 'lowest']
        exclude:
          - php: '8.3'
            mode: 'lowest'

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies in stable mode
        if: matrix.mode == 'stable'
        run: composer update --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Install lowest supported dependencies in lowest mode
        if: matrix.mode == 'lowest'
        run: composer update --prefer-lowest --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run psalm
        run: php vendor/bin/psalm --long-progress --no-cache --output-format=compact --report="./checkstyle.xml" --report-show-info=false
